### ISSUE TITLE
Text "Jumping" by refreshing the page

### ISSUE THREAD

**Issue by Junkboy1** [onwidget/qwind#11]
Hello, I'm testing qwind template and I just clone the repo then npm i, npm run dev and when I join the page I see an instant "jump" of the text then I navigate to /blog and the go back to / and both times I see that the text jumps. 

To test it just clone the repo and run the dev env then press F5 and anytime that you press F5 you will see the text jumping and its like "flashing" the screen

**Comment by Junkboy1** [comment]
I test it even in prod and its there

**Comment by prototypa** [comment]
Hello @Junkboy1 

That is due to changes with the fonts in what loads the one required by the theme. We replace the fonts sources from _Google Fonts_ to the packages `@fontsource/`. Now It should work without a problem.
