### ISSUE TITLE
Issues with Tailwindcss in production

### ISSUE THREAD

**Issue by Junkboy1** [onwidget/qwind#13]
I'm trying to use this template in my website and I'm facing issues with Tailwindcss. 

As you can see in the "npm run dev" it seems that everyting runs properly 

<img width="159" alt="image" src="https://github.com/onwidget/qwind/assets/125615430/a92e5f49-c220-4ee9-80d0-0d9efd097728">

BUT.. in prod I see this:
<img width="122" alt="image" src="https://github.com/onwidget/qwind/assets/125615430/d511a6c1-ec35-40f6-ae13-ce421a1cb448">

It has 100% transparency in prod.

**Comment by spectraisdeadaf** [comment]
Hey, I am trying to recreate your bug from a clean clone of this Repo and it seems to work as expected even in prod.
The only thing I can think off without further context is perhaps check your build settings, it could affect the way that the CSS looks. For example, if you have enabled minification, the CSS will be minified, which can sometimes lead to differences in the way that it looks from dev to prod.

**Comment by Junkboy1** [comment]
How can I check that about minification? I dont modify anything from the build settings @spectraisdeadaf

**Comment by prototypa** [comment]
Hi @Junkboy1 

It works fine for me in various environments. Please update to the latest version. I'm going to close this Issue, if the problem persists let me know. Thank you
