### ISSUE TITLE
Fresh install, after build, preview doesnt run. 

### ISSUE THREAD

**Issue by ohbob** [onwidget/qwind#15]
On clean install, after npm install, npm run build, npm run preview returns an error. 

ReferenceError: Cannot access 'bp' before initialization

**Comment by prototypa** [comment]
Hi @ohbob and @awaddell 

Thank you for this.

This template started with the early days of Qwik and had some outdated configuration files and functions. I just updated it: https://github.com/onwidget/qwind/commit/8a89aa8587684809774c25fe49d455400575e8a6
